#!/usr/bin/env node
// Write one blog post for one daily slot and record it.
//
//   node scripts/blog/generate.mjs --slot 0700
//   node scripts/blog/generate.mjs --slot 1800 --no-search
//   node scripts/blog/generate.mjs --slot 1100 --dry-run
//
// Flow:
//   1. load the slot's prompt (rules are verbatim in prompts/blog/)
//   2. gather topic candidates: daily digest (docs/data/latest.json),
//      optional web search (lib/search.mjs), memory logs
//   3. generate the article with the configured free-tier AI provider
//   4. save docs/blog/YYYY-MM-DD/<slot>.txt, append the log line to
//      memory/areas/github-trending-blog.md, rebuild docs/blog/index.json
//   5. print the article to stdout
//
// No external dependencies. Runs on a bare GitHub Actions runner.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import {
  SLOTS,
  SLOT_ORDER,
  appendLogLine,
  buildSystemPrompt,
  buildUserPrompt,
  dedupeParagraphs,
  extractLogline,
  extractTitle,
  rebuildIndex,
  sanitizeArticle,
  todayMYT,
} from './lib/core.mjs';
import { generateArticleText } from './lib/llm.mjs';
import { formatCandidates, searchCandidates } from './lib/search.mjs';
import { log, timeInZone, truncate, warn } from '../lib/util.mjs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..');
const BLOG_DIR = path.join(ROOT, 'docs', 'blog');
const MEMORY = path.join(ROOT, 'memory');

function parseArgs(argv) {
  const args = { slot: null, date: null, search: true, dryRun: false };
  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i];
    if (arg === '--slot') args.slot = argv[++i];
    else if (arg === '--date') args.date = argv[++i];
    else if (arg === '--no-search') args.search = false;
    else if (arg === '--search') args.search = true;
    else if (arg === '--dry-run') args.dryRun = true;
    else {
      console.error(`不明な引数: ${arg}`);
      process.exit(2);
    }
  }
  return args;
}

function safeRead(file) {
  try {
    return fs.readFileSync(file, 'utf8');
  } catch {
    return '';
  }
}

function readDigestCandidates() {
  const file = path.join(ROOT, 'docs', 'data', 'latest.json');
  let data;
  try {
    data = JSON.parse(safeRead(file));
  } catch {
    return { tools: [], news: [], date: '' };
  }
  const tools = (data.tools || []).slice(0, 5).map((tool) => ({
    name: tool.name,
    url: tool.url,
    description: tool.description,
    headline: tool.headline,
  }));
  const news = (data.news || []).slice(0, 8).map((item) => ({
    title: item.title,
    titleJa: item.titleJa,
    url: item.url,
    summary: item.summary,
  }));
  return { tools, news, date: data.dateLocal || '' };
}

/** Titles of the posts already generated by this system (index.json). */
function readRecentTitles(limit = 40) {
  let entries;
  try {
    entries = JSON.parse(safeRead(path.join(BLOG_DIR, 'index.json')));
  } catch {
    return '';
  }
  if (!Array.isArray(entries)) return '';
  return entries
    .slice(0, limit)
    .map((entry) => `${entry.date} [${entry.label}] ${entry.title}`)
    .join('\n');
}

/** Titles of today's earlier slots — the model must not step on them. */
function readTodayTitles(date) {
  const dayDir = path.join(BLOG_DIR, date);
  let files = [];
  try {
    files = fs.readdirSync(dayDir).filter((name) => name.endsWith('.txt')).sort();
  } catch {
    return '';
  }
  return files
    .map((file) => extractTitle(safeRead(path.join(dayDir, file))) || file)
    .join('\n');
}

async function main() {
  const args = parseArgs(process.argv.slice(2));
  const slot = SLOTS[args.slot];

  if (!slot) {
    console.error([
      '使い方: node scripts/blog/generate.mjs --slot <id> [--date YYYY-MM-DD] [--no-search] [--dry-run]',
      `枠の指定は必須です。次のいずれか: ${SLOT_ORDER.join(', ')}`,
      ...SLOT_ORDER.map((id) => `  ${SLOTS[id].label}  →  --slot ${id}`),
    ].join('\n'));
    process.exit(2);
  }

  const date = args.date || todayMYT();
  log(`blog: ${slot.label} の記事を生成します (${date})`);

  // 1. Rules.
  const promptDir = path.join(ROOT, 'prompts', 'blog');
  const common = slot.usesCommon ? safeRead(path.join(promptDir, 'common.md')) : '';
  const slotPrompt = safeRead(path.join(promptDir, slot.prompt));
  if (!slotPrompt.trim()) {
    console.error(`プロンプトが読めません: prompts/blog/${slot.prompt}`);
    process.exit(1);
  }

  // 2. Memory + history.
  const pcSetup = safeRead(path.join(MEMORY, 'topics', 'pc-setup.md'));
  const devEnvironment = safeRead(path.join(MEMORY, 'topics', 'dev-environment.md'));
  const writerNote = safeRead(path.join(MEMORY, 'people', 'humble-bobcat51.md'));
  const memoryLog = safeRead(path.join(MEMORY, 'areas', 'github-trending-blog.md'));
  const memoryArchive = safeRead(path.join(MEMORY, 'areas', 'blog-log-archive.md'));
  const noteTitles = safeRead(path.join(MEMORY, 'note-titles.txt'));
  const recentTitles = readRecentTitles();
  const todayTitles = readTodayTitles(date);

  // 3. Candidates: daily digest + optional web search.
  const digest = readDigestCandidates();
  if (digest.date) log(`blog: ダイジェスト候補 (${digest.date}) — tools ${digest.tools.length} / news ${digest.news.length}`);
  let search = [];
  if (args.search) {
    search = await searchCandidates(slot.queries, { num: 8, recencyDays: 7 });
  } else {
    log('blog: --no-search のため検索をスキップ');
  }
  const candidates = formatCandidates({ tools: digest.tools, news: digest.news, search });

  // 4. Generate (one retry when the model hands back a stub).
  const system = buildSystemPrompt();
  const user = buildUserPrompt({
    date,
    slot,
    common,
    slotPrompt,
    pcSetup,
    devEnvironment,
    writerNote,
    log: memoryLog,
    archive: memoryArchive,
    noteTitles,
    recentTitles,
    todayTitles,
    candidates,
  });

  let { text, provider, model } = await generateArticleText({ system, user });
  log(`blog: 生成完了 (${provider}/${model}, ${text.length} 文字)`);

  let { article, logline } = extractLogline(text);
  article = dedupeParagraphs(sanitizeArticle(article));

  if (article.length < 1500) {
    warn(`blog: 本文が短すぎます (${article.length} 字) — 指定を強めて1回だけ再生成します`);
    const retryUser = [
      user,
      '【重要】直前の出力は本文が短すぎました。最初から書き直してください。',
      '本文は3500〜4500字。仕組みの中身、どこが新しいか、どこが微妙か、うちの非力なPCではどうかを具体的に膨らませて。',
      'ハッシュタグ5個前後の行と、最後の ===LOGLINE=== ブロックも必ずつけて。',
    ].join('\n');
    try {
      const retry = await generateArticleText({ system, user: retryUser });
      const retryParsed = extractLogline(retry.text);
      const retryArticle = dedupeParagraphs(sanitizeArticle(retryParsed.article));
      if (retryArticle.length > article.length) {
        article = retryArticle;
        logline = retryParsed.logline || logline;
        provider = retry.provider;
        model = retry.model;
        log(`blog: 再生成を採用 (${provider}/${model}, ${article.length} 字)`);
      }
    } catch (error) {
      warn(`blog: 再生成に失敗したため初回を採用します — ${error.message}`);
    }
  }

  const title = extractTitle(article);

  if (!title || article.length < 300) {
    console.error('blog: 記事が短すぎるか空です。生成に失敗とみなします。');
    console.error(truncate(article, 400));
    process.exit(1);
  }
  if (!logline) {
    warn('blog: ===LOGLINE=== ブロックが無かったので代替行を作ります');
    logline = `${date} ${slot.logTemplate}`;
    logline = logline.replace('何をするものか一行', truncate(title, 40))
      .replace('何をするやり方か一行', truncate(title, 40))
      .replace('何の話か一行', truncate(title, 40))
      .replace('拾ったソース', 'ソース:記載なし')
      .replace('読んだ一次情報', '一次情報:記載なし')
      .replace('うちのPCで動きそうかどうか', '不明')
      .replace('うちのPCで試せそうかどうか', '不明')
      .replace('証拠の強さの見立て', '見立てなし')
      .replace('重要だと判断したところと、そうでもないと判断したところ', '判断なし');
  }

  // 5. Persist (unless dry-run) + print the article as the reply body.
  if (args.dryRun) {
    log('blog: --dry-run のため保存しません');
  } else {
    const dayDir = path.join(BLOG_DIR, date);
    fs.mkdirSync(dayDir, { recursive: true });
    const file = path.join(dayDir, `${slot.fileBase}.txt`);
    fs.writeFileSync(file, `${article.replace(/\s*$/, '\n')}`);
    log(`blog: 保存 → docs/blog/${date}/${slot.fileBase}.txt`);

    appendLogLine(path.join(MEMORY, 'areas', 'github-trending-blog.md'), logline);
    log(`blog: ログ追記 → memory/areas/github-trending-blog.md`);

    const entries = rebuildIndex(path.join(ROOT, 'docs'));
    log(`blog: index.json 更新（${entries.length} 本）`);
  }

  process.stdout.write(`\n${article}\n`);
  process.stderr.write(`\n[logline] ${logline}\n`);
  process.stderr.write(`[done] ${slot.label} @ ${timeInZone(new Date(), 'Asia/Kuala_Lumpur')}\n`);
}

main().catch((error) => {
  console.error(`blog: 生成に失敗しました — ${error.message}`);
  process.exit(1);
});
